# Generated by Django 5.2.3 on 2025-06-25 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Garçon'), ('F', 'Fille')], max_length=1)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_administration', models.DateField()),
                ('statut', models.CharField(choices=[('recu', 'Reçu'), ('retard', 'Retard')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccins', to='vaccination.enfant')),
            ],
        ),
        migrations.AddField(
            model_name='enfant',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='vaccination.village'),
        ),
    ]
